### ISSUE TITLE
`useEnterprise` config option breaks `useRecaptchaNet` unnecessarily

### ISSUE THREAD

**Issue by MaximusHaximus** [t49tran/react-google-recaptcha-v3#103]
This package disables using `recaptcha.net` when configured with `useEnterprise: true`, even if it was _also_ configured with `useRecaptchaNet: true`.

However, ReCAPTCHA Enterprise can be loaded from either `google.com` or `recaptcha.net`; there is no reason to load Enterprise ReCAPTCHA from `google.com`.

Because of this behaviour, this package breaks for any users in China (for example), when it is configured to use Enterprise ReCAPTCHA, even though it _would_ work fine if the package used `recaptcha.net` to load it instead of ignoring how the `useRecaptchaNet` configuration option is set. :)

Opened #102 with a fix for this issue. :)

**Comment by sambouchard** [comment]
Is this published in the 1.9.5 version or do you we Have to wait for the 1.9.6 release for it to be available?
