### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by liviuzachin** [t49tran/react-google-recaptcha-v3#135]
[Here](https://github.com/t49tran/react-google-recaptcha-v3/blob/master/src/utils.ts#L148) must check if `process` is defined too. Getting `ReferenceError: process is not defined` in production.

**Comment by viliuscicenas** [comment]
I think this issue was mentioned in here #107 and it seems it is ignored for  a while, technically that code could be just wrapped in try catch block as it is non-essential code in my opinion

**Comment by liviuzachin** [comment]
I see, in my case it crashed my whole Remix app and took a while to find out the root cause. Thanks.
