### ISSUE TITLE
TypeError: Cannot read property 'ready' of undefined

### ISSUE THREAD

**Issue by ErcinDedeoglu** [t49tran/react-google-recaptcha-v3#15]
**Getting error:**
`TypeError: Cannot read property 'ready' of undefined
`
**My code:**
```
ReactDOM.render(
    <GoogleReCaptchaProvider
        reCaptchaKey="xx"
    >
        <Provider store={configureStore()}>
        <Suspense fallback={<div className="loading" />}>
          <App />
        </Suspense>
      </Provider>
    </GoogleReCaptchaProvider>,
  document.getElementById('root')
);
```

**Call:**
```
  componentDidMount() {
    window.grecaptcha.ready(function() {
      window.grecaptcha.execute('xx', {action: action}).then(function(value) {
        token.currentRecaptchaToken = value;
        console.log(token);
      });
    });
  }
```

How can I understand component loaded successfully? Thanks advance.

**Comment by t49tran** [comment]
How the library can be used has already been written in the document, please check it before open issue.

The type error you are experiencing is not part of the library. In fact, you are not supposed to use `window.grecaptcha`.

The library expose component, `HOC` and hooks that you can use to in your React code, please check the document for these information.
