### ISSUE TITLE
Cannot invoke an object which is possibly 'undefined'.  TS2722

### ISSUE THREAD

**Issue by lordh1** [t49tran/react-google-recaptcha-v3#16]
Hi

```
const { executeRecaptcha } = useGoogleReCaptcha();
executeRecaptcha("").then(data => console.log(data));
```
is causing an error because `executeRecaptcha` is optional here:

```
export interface IGoogleReCaptchaConsumerProps {
    executeRecaptcha?: (action?: string) => Promise<string>;
}
```

**Comment by t49tran** [comment]
You can check the example to see how this is handle.

You should always check to see if `executeRecaptcha` is ready first before invoke it. `executeRecaptcha` is optional as it's dependent on the google library which is loaded asynchronously,.

**Comment by kafeltz** [comment]
For me is forever undefined this var and the app never work.
If i call it by console I can retrieve the value.

The example don't work for me.

![image](https://user-images.githubusercontent.com/1765469/78273748-a868e180-74e5-11ea-92ba-07f63643f675.png)

**Comment by danmoore83** [comment]
FYI for anyone having the same problem. 
I was having this issue with it always being undefined.
However this turned out to be my own fail, with incorrect dependencies when using useCallback.

**Incorrect:** 
```
  const { executeRecaptcha } = useGoogleReCaptcha();

  const handleReCaptcha = useCallback( async() => {
    if (!executeRecaptcha) return;

    const token = await executeRecaptcha('pollVote');
    handleVote(selection, token);
  }, [ executeRecaptcha, selection ] );

  const onSubmit = useCallback(async(e) => {
    e.preventDefault();
    if (isApp) {
      handleVote(selection);
    } else {
      handleReCaptcha();
    }
  }, [ isApp, selection ]);

```

In my onsubmit function I didnt list the handleReCaptcha function as a dependency, resulting in it using a memoised version from when executeRecaptcha was undefined.

**Working:**
```
  const { executeRecaptcha } = useGoogleReCaptcha();

  const handleReCaptcha = useCallback( async() => {
    if (!executeRecaptcha) return;

    const token = await executeRecaptcha('pollVote');
    handleVote(selection, token);
  }, [ executeRecaptcha, selection, handleVote ] );

  const onSubmit = useCallback(async(e) => {
    e.preventDefault();
    if (isApp) {
      handleVote(selection);
    } else {
      handleReCaptcha();
    }
  }, [ handleReCaptcha, handleVote, isApp, selection ]);

```

**Comment by pereriksson** [comment]
If anyone is coming here from Google, I solved this by moving my Recaptcha higher order component higher up in the hierarchy. My guess is that this component should never be rerendered.

**Comment by eabdollahian** [comment]
I get the same error. And When I log executeRecaptcha this shows me.
`ƒ (e){if(!C||!C.execute)throw new Error("<GoogleReCaptchaProvider /> Google Recaptcha has not been loaded");return C.execute(x.current,{action:e})}`
I used this trick and I think the problem is gone:

const handleRecaptcha = useCallback(async () => { 
 if (!executeRecaptcha) {
      console.log("Execute recaptcha not yet available");
      return;
    }
try {
      const token = await executeRecaptcha("homepage");
      console.log("token", token);
      if (token) {
//do sth
    }
} catch (e) {
      console.log(e);
      setTimeout(() => handleRecaptcha(), 100);
    }
},[executeRecaptcha]);

**Comment by gybber-dev** [comment]
> If anyone is coming here from Google, I solved this by moving my Recaptcha higher order component higher up in the hierarchy. My guess is that this component should never be rerendered.

Can you write a code example?

**Comment by pereriksson** [comment]
> > If anyone is coming here from Google, I solved this by moving my Recaptcha higher order component higher up in the hierarchy. My guess is that this component should never be rerendered.
> 
> Can you write a code example?

Instead of wrapping the component that contains the form (which might be rerendered), we moved it higher up in the hierarchy in our Next.js repo to the app component instead, which solved the issue for us.
```
const App = (props) => {
  return (
      <Head>
        <title>Title</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <GoogleReCaptchaProvider
          reCaptchaKey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        >
          <Component {...pageProps} />
        </GoogleReCaptchaProvider>
        <ScrollButton />
        <GDPRMsg />
      </ThemeProvider>
  );
};
```

Hope this helps.
