### ISSUE TITLE
Handle expired token

### ISSUE THREAD

**Issue by sanderdewijs** [t49tran/react-google-recaptcha-v3#18]
Hi, 

Is it possible to trigger the validation and generated token when the user performs and action? For example when submitting a form? 

In my usecase, the entire website is rendered in React. So there can be several minutes between when the user visits the site, and decides to submit the form. The token is expired by then.

**Comment by t49tran** [comment]
@sanderdewijs, please read and follow the doc. You can either use the hook `useGoogleReCaptcha` or the HOC `withGoogleReCaptcha`, to access the `executeRecaptcha` function and generate a token programatically.

**Comment by tractorcow** [comment]
I managed to solve this in my project without a custom hook; I just conditionally load the recaptcha after my form is submitted.

```js
                <div className="form-field">
                  {completeForm && (
                    <GoogleReCaptcha
                      action="contact"
                      onVerify={token =>
                        submitForm(values, setSubmitting, token)
                      }
                    />
                  )}
                </div>
```

where `completeForm` is a state I set to true once I click `submit` (using Formik)

**Comment by t49tran** [comment]
> I managed to solve this in my project without a custom hook; I just conditionally load the recaptcha after my form is submitted.
> 
> ```js
>                 <div className="form-field">
>                   {completeForm && (
>                     <GoogleReCaptcha
>                       action="contact"
>                       onVerify={token =>
>                         submitForm(values, setSubmitting, token)
>                       }
>                     />
>                   )}
>                 </div>
> ```
> 
> where `completeForm` is a state I set to true once I click `submit` (using Formik)

Hi @tractorcow, if you need to submit the recaptcha when the form is **completed**, it's better to either use the hook `useGoogleReCaptcha` or the HOC `withGoogleReCaptcha` to access to the function `excecuteRecaptcha`.

A submit handler with Formik should look like:
```javascript
const handleSubmit = async (formData) => {
    const token = await executeRecaptcha('YOUR_RECAPTCHA_ACTION');
   // You can use the token here with your submit function
}
``` 

While you can do it the way as in your code example, the `GoogleRecaptcha` component is not designed to run that way, and I could say it is not recommended. It creates a chain of dependency between several asynchronous functions which should all be combined into a single one.

**Comment by tractorcow** [comment]
Yes you are right; After I posted that solution, I did more extensive testing and found it had severe issues (multiple posting per form submission).

The correct soultion was to not use the react component at all.

I like my promises, rather than using async / await, so my code looks like this for submit:

```js
return executeRecaptcha('contact').then(token => { /* graphql submit form with 'token' */ });
```

then I had a graphql mutation that would validate the token on the serverside, and create the form submission.

**Comment by tractorcow** [comment]
Just to be nice, here's my PHP for serverside token validation.


```php
    /**
     * Verify a recaptcha token
     *
     * @param $token
     * @throws ValidationException
     */
    protected function verifyRecaptcha($token)
    {
        // Validate recaptcha
        $request = $this->getRequest();
        $recaptcha = new ReCaptcha($this->getEnv('APP_RECAPTCHA_SECRET'));
        $recaptchaResponse = $recaptcha
            ->setExpectedHostname($this->getFrontendHostname())
            ->verify(
                $token,
                $request->getIP()
            );
        if (!$recaptchaResponse->isSuccess()) {
            throw new ValidationException(
                "Invalid recaptcha response: " . implode(',', $recaptchaResponse->getErrorCodes())
            );
        }
    }
```
