### ISSUE TITLE
Recaptcha Element isn't visible when hook is used

### ISSUE THREAD

**Issue by skoob13** [t49tran/react-google-recaptcha-v3#19]
Hello,

We have noticed that when we use HOC/Hook or context the Recaptcha element doesn't appear at all. However, when we use a component the element is visible. I'm not sure that there is a bug, but according to Recaptcha V3 [docs](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed) we should show the element or additional labels.

Shouldn't hocs/hooks/context have the same behavior as component?

Thanks for the package!

**Comment by t49tran** [comment]
Hi @skoob13, I am not sure what you mean when you're referring to `the element`.

If you mean the Google Recaptcha label  then it should be visible by default when used with `withGoogleReCaptcha` or `useGoogleRecaptcha` .

<img width="844" alt="Screen Shot 2020-01-28 at 5 39 05 pm" src="https://user-images.githubusercontent.com/2223362/73257838-113a9180-41f7-11ea-8868-0ed83a3af0cb.png">

**Comment by skoob13** [comment]
@t49tran I'm sorry for the wrong report, it was the issue on our side
