### ISSUE TITLE
How hide badge

### ISSUE THREAD

**Issue by difagume** [t49tran/react-google-recaptcha-v3#22]
Hey, thanks for making this package.
I'm using it in the login page but when I enter the dashboard the component is still there, I would like to know how to make it only appear in my login page, or how I can hide it, thank you very much.

My code

**App.tsx**
```
return (
    <GoogleReCaptchaProvider reCaptchaKey={process.env.REACT_APP_RECAPTCHA_KEY}>
      <ApolloProvider client={client}>
        <Routes />
      </ApolloProvider>
    </GoogleReCaptchaProvider>
  );
```

**Login.tsx**

```
export const Login: React.FC<RouteComponentProps> = ({ history }) => {
  const { executeRecaptcha } = useGoogleReCaptcha();

async function uLogin() {
    if (!executeRecaptcha) {
      return;
    }
    const result = await executeRecaptcha("login_page");
    setToken(result);
    console.log('token', result);
...
}

return {...}
}
```

**Comment by michalkobelka** [comment]
Add `.grecaptcha-badge { display: none; }` to your CSS

**Comment by anhtran** [comment]
As mention in https://stackoverflow.com/a/53986985/186153

You also have to add links to the terms.

**Comment by difagume** [comment]
My intention was to show the recaptcha component on the login page so the option to add "display: none" didn't help much.

What I did was to use: **useLayoutEffect** both in login.tsx and in the home.tsx page where I was going to hide it, if it helps someone I did it like this:

**Login.tsx**
```
useLayoutEffect(() => {
    // muestro div del recaptcha
    const captcha: any = document.getElementsByClassName('grecaptcha-badge')[0];
    if (captcha) {
      captcha.style.removeProperty('visibility')
    }
  }, [])
```

**Home.tsx**
```
useLayoutEffect(() => {
    const captcha: any = document.getElementsByClassName('grecaptcha-badge')[0];
    if (captcha) {
      captcha.style.visibility = 'hidden';
    }
  }, [])
```

Any correction is welcome
