### ISSUE TITLE
Problem using the hook

### ISSUE THREAD

**Issue by aebmknrl** [t49tran/react-google-recaptcha-v3#24]
Hello friend, first of all I wanted to thank you for making this library.

The implementation of the hook is not very clear to me.

this line:
`  const token = executeRecaptcha("login_page");`

returns a `promise`. So if I add the async/await to this function (`ReCaptchaComponent `) I have an error rendering the component... Because this function must contains the analysis of the response from server (the score) and must return a component... right?
Something like this: ?

```
import {
  GoogleReCaptchaProvider,
  useGoogleReCaptcha
} from 'react-google-recaptcha-v3';

// Remember that the hook can only be used within a React functional component
const ReCaptchaComponent = async () => {
  const { executeRecaptcha } = useGoogleReCaptcha();
  const token = await executeRecaptcha("login_page");
  if(token.score (?) > 0.5  ){
     return <MyComponent/>
  else {
      return <MyComponentWithAMessage /> // Component that will show a 'denied' or something like this
   }
}

ReactDom.render(
  <GoogleReCaptchaProvider reCaptchaKey="[Your recaptcha key]">
    <ReCaptchaComponent />
  </GoogleReCaptchaProvider>,
  document.getElementById('app')
);
```

Is this a correct way? Thanks a lot.

**Comment by t49tran** [comment]
Hi Ali, the issue you posted has nothing to do with the way with the hook has been implemented. 

Basically, I think you're confused about about how to handle asynchronous and conditional rendering in React. I reckon you read the React document to have a better understanding. 

Also, I believe you're also confused about how Google Recaptcha v3 works, basically, in the browser, the `excecuteRecaptcha` function will only return a token. This token then will usually be sent to a backend to verify, only after that Google give you a score.  You can read more about the topic here https://developers.google.com/recaptcha/docs/verify.

> Because this function must contains the analysis of the response from server (the score) and must return a component... right?

The way the library is designed is to help developers to get a recaptcha token, what he / she decides to do with that token is out of the scope of the library. 

Regarding your example, I can give a brief example of how I should implement something like this:

const ReCaptchaComponent = () => {
  const { executeRecaptcha } = useGoogleReCaptcha();
  const [recaptchaScore, setRecaptchaScore] = useRecaptchaScore();

  const handleExecuteRecaptcha = async () => {
     const token = await executeRecaptcha("login_page");

     // You will need to decide how to verify the token and get a score yourself
     const score = await verifyTheScoreInYourOwnWay();
     setRecaptchaScore(score);
  };

  React.useEffect(() => {
    handleExecuteRecaptcha();
  }, []);
  
  return recaptchaScore > 0.5 ? <MyComponent/> : <MyComponentWithAMessage />;
}
