### ISSUE TITLE
Use in Japan

### ISSUE THREAD

**Issue by D-Thrane** [t49tran/react-google-recaptcha-v3#25]
Japan blocks google. Is there any way to support China with the other url supported by google for China use.

**Comment by Dashiing** [comment]
This solves it:
Extend GoogleReCaptchaProvider and use the new extended class instead:
```javascript
import { GoogleReCaptchaProvider } from 'react-google-recaptcha-v3';

export class GoogleRecaptchaProviderGlobal extends GoogleReCaptchaProvider {
     googleRecaptchaSrc = 'https://www.recaptcha.net/recaptcha/api.js';
}
```
Now it make use of the **recaptcha.net** url instead of **google.com** which is blocked in china.
