### ISSUE TITLE
ReferenceError while running example code

### ISSUE THREAD

**Issue by bogdancss** [t49tran/react-google-recaptcha-v3#27]
Hey there,

While running the example, I am getting the following reference error: 

`recaptcha.js:18 Uncaught ReferenceError: regeneratorRuntime is not defined`

**Comment by t49tran** [comment]
It looks like a problem with your bundler / compiler rather than the library itself.

**Comment by bogdancss** [comment]
@t49tran this was recreated just by importing the package in a barebone create-react-app project
