### ISSUE TITLE
Should have functionality to hide and display captcha badge

### ISSUE THREAD

**Issue by VishalSalunke** [t49tran/react-google-recaptcha-v3#28]
I know as per google terms we can not directly hide the captcha badge, But on the other hand we don't want captcha badge all the time. 
You should add some prop or something so that we can show badge only when the user is filling the form and after submitting the form we can hide badge.

There are other ways of doing this like
document.getElementsByClassName('grecaptcha-badge')[0].style.opacity = 0
But this is not react way to achieve it

**Comment by t49tran** [comment]
That's problem should now be resolved in with the latest version 1.5.1.
