### ISSUE TITLE
Feature Request: Possibility to hide banner

### ISSUE THREAD

**Issue by ohlr** [t49tran/react-google-recaptcha-v3#36]
`.grecaptcha-badge { visibility: hidden; }`
hides the banner and is allowed as long 

```
This site is protected by reCAPTCHA and the Google
    <a href="https://policies.google.com/privacy">Privacy Policy</a> and
    <a href="https://policies.google.com/terms">Terms of Service</a> apply.
```
is provided on the form (https://developers.google.com/recaptcha/docs/faq)

I'd love to see this feature with a invisible=true || false flag. Should be fine, when referencing the faq in the docs

**Comment by t49tran** [comment]
This has been discussed before and I will not include it as part of this library. The developer can choose to hide the badge if they want and it's pretty easy to do.

**Comment by LouiseReid** [comment]
Wheres the documentation on how to do this?

**Comment by leopucci** [comment]
> Wheres the documentation on how to do this?

It is just a .css code to add. I really don´t know why this is not on the module. 
Professional sites will not use the badge anyway. Why not make a professional module also?

`.grecaptcha-badge { 
    visibility: hidden;
}`

WARNING: display: none DISABLES the spam checking!
https://stackoverflow.com/a/53986985/3156756
