### ISSUE TITLE
On IE browser, it is giving "SCRIPT5002: Invalid operand to 'instanceof': Function expected" at recaptcha_en.js (553,39)

### ISSUE THREAD

**Issue by neha-takhi** [t49tran/react-google-recaptcha-v3#37]
On IE, it is giving error, if you leave the page untouched for while.

**Comment by t49tran** [comment]
@neha-takhi which version of IE are you using ?

**Comment by neha-takhi** [comment]
Hi , I am using IE 11

**Comment by neha-takhi** [comment]
Please help me out in this. In recaptcha_en.js, where we are using instanceOf it is giving error.

**Comment by neha-takhi** [comment]
![recaptchaBug](https://user-images.githubusercontent.com/48908600/83859572-bf24f200-a73b-11ea-8a50-f3394e07210d.PNG)
![recaptchaBug](https://user-images.githubusercontent.com/48908600/83859588-c4823c80-a73b-11ea-891c-557e1369414c.PNG)

**Comment by t49tran** [comment]
@neha-takhi, supporting IE 11 is not my top priority. Feel free to submit a PR if you have a solution. Otherwise I will address it when I have time.

**Comment by dmorda** [comment]
I'm running into the same issue. I believe it has to do with the remove() method on line 77 of [google-recaptcha-provider.tsx](https://github.com/t49tran/react-google-recaptcha-v3/blob/master/src/google-recaptcha-provider.tsx#L77). Unfortunately, I'm not sure I know what would need to change to address the issue, but maybe it's enough to provide a lead.

**Comment by t49tran** [comment]
IE 11 is not going to receive any support from MS by November, there is very little reason for me to support IE 11.

Sorry about that but supporting an out-of-date, infamous for non-standard issues browser is not on my list.
