### ISSUE TITLE
Timeout for executeRecaptcha on Mobile Chrome

### ISSUE THREAD

**Issue by ohlr** [t49tran/react-google-recaptcha-v3#39]
On my Smartphone Chrome 
` const token = await executeRecaptcha("contact");`

fails with a timeout (Stacktrace below)
It works fine on Mozilla and Desktop versions of chrome other mobile versions of chrome.
The issue is probably located upstream. But this might be a good starting point.

Chrome is 83.0.4103.106
Android 10

```
  | __stack_frame_overlay_proxy_console__ | @ | index.js:2177
-- | -- | -- | --
  | (anonymous) | @ | recaptcha__en.js:92
  | Promise.catch (async) |   |  
  | (anonymous) | @ | recaptcha__en.js:92
  | (anonymous) | @ | recaptcha__en.js:132
  | h.<computed>.next | @ | recaptcha__en.js:156
  | (anonymous) | @ | recaptcha__en.js:326
  | (anonymous) | @ | recaptcha__en.js:326
  | (anonymous) | @ | recaptcha__en.js:131
  | (anonymous) | @ | recaptcha__en.js:91
  | (anonymous) | @ | recaptcha__en.js:206
  | (anonymous) | @ | react-google-recaptcha-v3.esm.js:105
  | Promise.then (async) |   |  
  | (anonymous) | @ | react-google-recaptcha-v3.esm.js:104
  | step | @ | react-google-recaptcha-v3.esm.js:75
  | (anonymous) | @ | react-google-recaptcha-v3.esm.js:56
  | (anonymous) | @ | react-google-recaptcha-v3.esm.js:49
  | __awaiter | @ | react-google-recaptcha-v3.esm.js:45
  | GoogleReCaptchaProvider._this.executeRecaptcha | @ | react-google-recaptcha-v3.esm.js:100
  | _callee$ | @ | SubscribeFooter.tsx:105
  | tryCatch | @ | runtime.js:45
  | invoke | @ | runtime.js:274
  | prototype.<computed> | @ | runtime.js:97
  | asyncGeneratorStep | @ | asyncToGenerator.js:3
  | _next | @ | asyncToGenerator.js:25
  | (anonymous) | @ | asyncToGenerator.js:32
  | (anonymous) | @ | asyncToGenerator.js:21
  | onSubmit | @ | SubscribeFooter.tsx:105
  | (anonymous) | @ | react-hook-form.es.js:1215
  | async function (async) |   |  
  | (anonymous) | @ | react-hook-form.es.js:1199
  | callCallback | @ | react-dom.development.js:189
  | invokeGuardedCallbackDev | @ | react-dom.development.js:238
  | invokeGuardedCallback | @ | react-dom.development.js:293
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.development.js:307
  | executeDispatch | @ | react-dom.development.js:390
  | executeDispatchesInOrder | @ | react-dom.development.js:415
  | executeDispatchesAndRelease | @ | react-dom.development.js:3279
  | executeDispatchesAndReleaseTopLevel | @ | react-dom.development.js:3288
  | forEachAccumulated | @ | react-dom.development.js:3260
  | runEventsInBatch | @ | react-dom.development.js:3305
  | runExtractedPluginEventsInBatch | @ | react-dom.development.js:3515
  | handleTopLevel | @ | react-dom.development.js:3559
  | batchedEventUpdates$1 | @ | react-dom.development.js:21872
  | batchedEventUpdates | @ | react-dom.development.js:796
  | dispatchEventForLegacyPluginEventSystem | @ | react-dom.development.js:3569
  | attemptToDispatchEvent | @ | react-dom.development.js:4268
  | dispatchEvent | @ | react-dom.development.js:4190
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11040
  | discreteUpdates$1 | @ | react-dom.development.js:21888
  | discreteUpdates | @ | react-dom.development.js:807
  | dispatchDiscreteEvent | @ | react-dom.development.js:4169

```

**Comment by jpomykala** [comment]
I have the same problem but it happens on multiple web browsers including Safari and Firefox. I think this project is not maintained anymore 😢

**Comment by ohlr** [comment]
@jpomykala are you using pure react or some form of server side rendering (Gatsby, next...)

**Comment by jpomykala** [comment]
@ohlr Pure react

**Comment by ohlr** [comment]
Okay, I'm on gatsby - thought it might be related to that but obviously it's not

**Comment by ohlr** [comment]
https://stackoverflow.com/questions/62750901/recaptcha-timeouts-on-some-browsers

**Comment by ohlr** [comment]
@jpomykala Is your page an Accelerated Mobile Page? there is an additional checkbox in recaptcha console for such pages

**Comment by jpomykala** [comment]
@ohlr No, I'm using this on page without AMP

**Comment by t49tran** [comment]
> I have the same problem but it happens on multiple web browsers including Safari and Firefox. I think this project is not maintained anymore 😢

Hi @jpomykala, misleading and wrong information like this is not welcome. While I will try to address problem related to this library, please remember that it's an open-source project and it's not my responsibility or your entitlement that I have to address or fix your problem immediately.

It's an open source project, which means if you really care about it or the problem that you're facing, feel free to look at the codebase, debug, provide a solution and share it with others instead of crying and expect others to fix everything for you.

**Comment by jpomykala** [comment]
This is a chart showing reCaptcha timeouts in last 30 days. 
<img width="334" alt="Screenshot 2020-07-06 at 08 57 55" src="https://user-images.githubusercontent.com/1548104/86573213-587e3880-bf74-11ea-8494-23c8c8be66e2.png">

**Comment by t49tran** [comment]
@jpomykala , what is the context of the chart, what are the parameters it measures again ? The latest version of this lib is published last month.

https://www.npmjs.com/package/react-google-recaptcha-v3

Please get your thing right before provide misleading claim.

**Comment by jpomykala** [comment]
@t49tran Hey, calm down. I'm just trying to find the problem here ;) because timeouts are showing not only on the Mobile Chrome but also on other web browsers including the desktop ones. So we can exclude that fact it's a just connection problem on mobile.

**Comment by t49tran** [comment]
Sorry @jpomykala, I don't see sharing false and misleading claim as finding and fixing problem. This kind of practice is not welcome in sharing / collaborative project. 

You also didn't answer my question on the chart.

**Comment by ohlr** [comment]
@t49tran do you see any potential starting point to debug this?

**Comment by unCleanCode** [comment]
Having the same timeout error, particularly when going through different pages with react-router and both pages have GoogleReCaptchaProvider
First page loads and returns captcha, but the second one pretty often doesn't even make a request to google, but returns "Timeout (n)" exception after around 10s

**Comment by t49tran** [comment]
> Having the same timeout error, particularly when going through different pages with react-router and both pages have GoogleReCaptchaProvider
> First page loads and returns captcha, but the second one pretty often doesn't even make a request to google, but returns "Timeout (n)" exception after around 10s

@unCleanCode `GoogleReCaptchaProvider` is supposed to load once per app, your React tree is supposed to only have once instance of it. It's a context provider and there should only be one google recaptcha context in your app. I have seen quite a few people to include it multiple times on their app, usually on several pages they want to have recaptcha, unfortunately it's not how it's designed. You should have the Provider at the top of your app, and use the `hook` or the HOC to have access to the function it's provided.

I will have to spend sometimes to look into what happened if you have more than one `GoogleReCaptchaProvider` in your React tree but it's not what it should be used.

**Comment by unCleanCode** [comment]
@t49tran thanks for detailed answer. But it's not exactly the case - I only have GoogleReCaptchaProvider once in a React tree. The reason I didn't put it on top level is that the banner in bottom right corner is displayed on all pages, rather than only the pages I use them on. This is a problem as it takes space and overlaps some UI elements, especially on mobile

So I made a separate component which can be added to specific page, and which would go out when the page is unmounted. I'm still making sure there are no 2 such components in a single moment in React tree, so that should be fine

**Comment by t49tran** [comment]
@unCleanCode thanks for your commend. I appreciate it. 

From what you have reported (and I have seen a few others report it as well) there might be a problem with the provider being loaded later on a specific page (rather than always be there). I will spend sometimes to investigate it and see if I can provide a fix this weekend.

In the meantime, if you can come up with a fix, please feel free to contribute.

**Comment by ohlr** [comment]
I load the provider once, wrapping the entire page.. still I am facing the issue

**Comment by archywillhe** [comment]
having the same problem too hmm

**Comment by mykong89** [comment]
Hmm I also having this problem. The funny thing is that I also got this exception when I was using different reCaptcha library.

**Comment by corncobb** [comment]
Can confirm that wrapping my entire app with `GoogleReCaptchaProvider` and NOT just the component that I needed, fixed the timeout issue for me.

**Comment by dimileeh** [comment]
I'm using Gatsby and I started to see ReCaptcha timeouts as well.

Thanks to @t49tran who pointed out that `GoogleReCaptchaProvider` should be loaded once per app. I had the `GoogleReCaptchaProvider` in my `layout.js` file the core `Layout` that's used across all pages.

However, as we know, in the latest version of Gatsby this `Layout` gets reloaded on navigations between pages.

I'm using `gatsby-plugin-top-layout` plugin, and when I moved `GoogleReCaptchaProvider` to its `TopLayout.js` file, the timeouts seem to have disappeared 🎉

**Comment by tractorcow** [comment]
With nextjs I've had some success with a mini HOC for injecting the provider, but still not doing it at the app level.

```js

const ContactUs = ({ page }) => <div />; /* my page component with form */

const withRecaptcaProvider = PageComponent => ({ page }) => (
  <GoogleReCaptchaProvider
    language="en"
    reCaptchaKey={page.recaptchaKey}
  >
    <PageComponent page={page} />
  </GoogleReCaptchaProvider>
);

export default withRecaptcaProvider(ContactUs);
```

**Comment by t49tran** [comment]
> I'm using Gatsby and I started to see ReCaptcha timeouts as well.
> 
> Thanks to @t49tran who pointed out that `GoogleReCaptchaProvider` should be loaded once per app. I had the `GoogleReCaptchaProvider` in my `layout.js` file – the core `Layout` that's used across all pages.
> 
> However, as we know, in the latest version of Gatsby this `Layout` gets reloaded on navigations between pages.
> 
> I'm using `gatsby-plugin-top-layout` plugin, and when I moved `GoogleReCaptchaProvider` to its `TopLayout.js` file, the timeouts seem to have disappeared 🎉

Hi @dimileeh , thanks for pointing that out, for Gatsby the problem can be solved by adding a top level wrapper such as the one added by top layout plugin. It's quite tricky and I think it's worth mentioning as Gatsby is quite popular. Feel free to open a PR to add a section to the ReadMe about Gatsby integration.

**Comment by t49tran** [comment]
> With nextjs I've had some success with a mini HOC for injecting the provider, but still not doing it at the app level.
> 
> ```js
> const ContactUs = ({ page }) => <div />; /* my page component with form */
> 
> const withRecaptcaProvider = PageComponent => ({ page }) => (
>   <GoogleReCaptchaProvider
>     language="en"
>     reCaptchaKey={page.recaptchaKey}
>   >
>     <PageComponent page={page} />
>   </GoogleReCaptchaProvider>
> );
> 
> export default withRecaptcaProvider(ContactUs);
> ```

Hi @tractorcow, thanks for reporting that. I have never used this plugin with Next.js and don't have much experience with Next.js, but will spend some time to investigate it.

**Comment by tractorcow** [comment]
@t49tran as long as I follow the instructions you gave (use the provider above the page level, or at the app level) it seems to work flawlessly.

**Comment by tractorcow** [comment]
Hm, I'm still having issues with the recaptcha timing out after 2 minutes (if I leave the form open). I am using serverside validation by the way, but the recaptcha only passes if I submit the form within 2 minutes.

**Comment by wbobeirne** [comment]
Looks like this is a long-standing issue with recaptcha-v3: https://github.com/google/recaptcha/issues/269

**Comment by t49tran** [comment]
Thanks for the info @wbobeirne, if there is a solution for this problem I am more than happy to implement it, or PRs to fix these problem are always welcomed.
