### ISSUE TITLE
Uncaught (in promise) TypeError: executeRecaptcha is not a function

### ISSUE THREAD

**Issue by alexllao** [t49tran/react-google-recaptcha-v3#44]
Hi!

`const result = await executeRecaptcha("homepage");
setRecaptchatoken(result); `

This code produces an error:

**_Uncaught (in promise) TypeError: executeRecaptcha is not a function_**

**Comment by t49tran** [comment]
Hi Alex, how do you get access to `executeRecaptcha` function ? Did you follow the document ? Can you provide the code where / how you get access to the function ?

**Comment by alexllao** [comment]
Hi!!!

In principle everything works well for me, the problem is that I would like to refresh the token in some way, since there is no other option than to update the page to have a new token.

**Comment by alexllao** [comment]
Sorry, I've already solved it. Thank you very much.

**Comment by alkhachatryan** [comment]
@alexllao how???
