### ISSUE TITLE
Should executeRecaptcha be possibly undefined? 

### ISSUE THREAD

**Issue by LuanGB** [t49tran/react-google-recaptcha-v3#48]
I have noticed that the IGoogleReCaptchaConsumerProps type has this property executeRecaptcha that can be possibly undefined. Should that be the case? For what I saw reading the code, there's no situation where executeRecaptcha will be undefined (It'll always be defined by googleReCaptchaContextValue).

https://github.com/t49tran/react-google-recaptcha-v3/blob/9c5608f0ab40d995fb433c9fa2151294637c9bb8/src/google-recaptcha-provider.tsx#L15

**Comment by LuanGB** [comment]
@t49tran I've sent this PR to fix the aforementioned issue. If you think something is missing, just let me know

**Comment by bencmbrook** [comment]
I've found that if the HOC is not present, it's `undefined`

**Comment by t49tran** [comment]
Hi @bencmbrook , that's something totally expected. I don't think it has anything to do with this PR though. Also, there is almost no reason to use HOC instead of hooks now. This library is predated the introduction of React hooks, therefore I keep the HOC for backward compatibility.
