### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by stfenjobs** [t49tran/react-google-recaptcha-v3#52]
warning " > react-google-recaptcha-v3@1.7.0" has incorrect peer dependency "react@^16.13".
warning " > react-google-recaptcha-v3@1.7.0" has incorrect peer dependency "react-dom@^16.13".

**Comment by a-mawlawi** [comment]
+1 for this

**Comment by t49tran** [comment]
Resolved in v1.7.1.
