### ISSUE TITLE
LightHouse, unused javascript

### ISSUE THREAD

**Issue by RenatoSerra22** [t49tran/react-google-recaptcha-v3#55]
Hello,

I've ran an lighthouse report on my site, which uses this lib and one of the main complaints lighthouse has is the size of recaptcha script and the amount of code unused.
I know the javascript is the one the lib gets from google, im wondering if theres any way to work around this?

<img width="755" alt="Screenshot 2020-11-27 at 11 38 48" src="https://user-images.githubusercontent.com/12633730/100445611-4b89ef00-30a5-11eb-9a00-ebb1ef1bc9b9.png">

Thank you

**Comment by t49tran** [comment]
I don't think there is anything you can do about that.

It's the same for any 3rd party scripts, there is no way to optimise them.
