### ISSUE TITLE
executeRecaptcha hangs when API key missing

### ISSUE THREAD

**Issue by bencmbrook** [t49tran/react-google-recaptcha-v3#56]
First of all, thanks for the awesome package. Makes reCAPTCHA much more usable :) 

My bug is that `executeRecaptcha` can hang. I suspect it's coming from the promise of `this.grecaptcha`.

I believe this code block might need to check whether recaptcha is ready?

https://github.com/t49tran/react-google-recaptcha-v3/blob/71256443cec4e75bd171045c0381b5fbc1423e70/src/google-recaptcha-provider.tsx#L95-L97

i.e. from the recaptcha docs https://developers.google.com/recaptcha/docs/v3#programmatically_invoke_the_challenge

```js
        grecaptcha.ready(function() {
          grecaptcha.execute('reCAPTCHA_site_key', {action: 'submit'}).then(function(token) {
              // Add your logic to submit to your backend server here.
          });
        });
```

I'm also looking into a similar issue where the API key _is_ defined, yet somehow it can still hang for me.

**Comment by t49tran** [comment]
Hi @bencmbrook , thanks for reporting the error. It seems to be a different problem, not related to the key to me.

If you check line https://github.com/t49tran/react-google-recaptcha-v3/blob/71256443cec4e75bd171045c0381b5fbc1423e70/src/google-recaptcha-provider.tsx#L57
and https://github.com/t49tran/react-google-recaptcha-v3/blob/71256443cec4e75bd171045c0381b5fbc1423e70/src/google-recaptcha-provider.tsx#L67

not providing a recaptcha key should result in a console  warning.

Also,  `this.grecaptcha` will be undefined until the recaptcha library is loaded and ready.
Do you mind posting your code that having the problem ?

**Comment by bencmbrook** [comment]
Thanks for quick response @t49tran. So, if I understand correctly, the absence of recaptcha key normally causes an early promise rejection?

The one thing I do know is that `await executeRecaptcha()` doesn't resolve or reject for me. I'll dig around and see if I can isolate whatever is happening down to something reproducible.

Does anything come to mind as to a particular condition where `await executeRecaptcha()` may not resolve/reject?

**Comment by t49tran** [comment]
Hi @bencmbrook , what you say is almost correct. If there is no recaptcha key, there will be no `grecaptcha`, you should see a warning in the console, and an error should be thrown out when you are trying to to call `executeRecaptcha` as it is undefined.

The hanging is actually might be something from Google, a few people have had this problem but I have never seen it myself or being able to replicate it (I tried to replicate it before). 

See that one for more information #39
