### ISSUE TITLE
Error: GoogleReCaptcha Context has not yet been implemented

### ISSUE THREAD

**Issue by horler234** [t49tran/react-google-recaptcha-v3#60]
I am getting this error `GoogleReCaptcha Context has not yet been implemented` when I use the `useGoogleReCaptcha` hook exactly the way it is in the documentation.

How can this be fixed?

**Comment by t49tran** [comment]
If you see that's error, it's likely that you haven't wrapped your application with the provider yet. Make sure that you've wrapped your application with the provider so the context is initialised. That's also what's the error means.

**Comment by horler234** [comment]
Thanks @t49tran. It totally works now.

**Comment by tanyaburlakova** [comment]
hello @t49tran :)

Could you please help me to understand if I need to call captcha on some pages where it needs, how I can do it?
Because I have tried to wrap pages with the captcha provider, but I got the same issue you described here.

Thank you.

**Comment by victor-cui-brigit** [comment]
do I need to wrap the entire app with the ` <GoogleReCaptchaProvider>` or only the component in which I need recaptcha?
