### ISSUE TITLE
Please clarify how to provide sitekey in production environment

### ISSUE THREAD

**Issue by CodingSpiderFox** [t49tran/react-google-recaptcha-v3#62]
How would I change the site key in different environments? 

The Readme says I should use a .env file for local testing but how would I provide the key in a staged environment (dev, staging, prod)?

**Comment by t49tran** [comment]
You should have used different .env file for different environment. It's pretty straight forward and natural if you understand that .env file is the file contains environment variables that will be different from env to env. 

I will close this one as it's not an issue of the library.
