### ISSUE TITLE
Please provide example where the captcha is solved automatically on form submit

### ISSUE THREAD

**Issue by CodingSpiderFox** [t49tran/react-google-recaptcha-v3#63]
I think it'll be a good idea to automatically submit the captcha when the user submits the form and prevent submitting the form when the captcha was not successful.

Could you please add a code example to the examples directory?

**Comment by t49tran** [comment]
That's one is out of the scope of the library. 

You should have checked the Google document to understand how Recaptcha v3 works: https://developers.google.com/recaptcha/docs/v3.

Basically there are two parts of it:
- The FE get a `recaptcha_token` from Google.
- This token needs to be sent to a backend (the developer backend), to be exchanged with Google for recaptcha information: https://developers.google.com/recaptcha/docs/v3#site_verify_response. With recaptcha v3, Google will not say whether the captcha is valid or not. It returns a `score` number and leaves the decision to the developer whether that score is good enough.
