### ISSUE TITLE
Captcha only for the specific pages.

### ISSUE THREAD

**Issue by tanyaburlakova** [t49tran/react-google-recaptcha-v3#64]
hello @t49tran :)

Could you please help me to understand if I need to call captcha on some pages where it needs, how I can do it?
Because I have tried to wrap pages with the captcha provider, but I got the Context issue that I need to wrap the whole app with the CaptchaProvider.

Thank you.

**Comment by t49tran** [comment]
Hi @tanyaburlakova, that question has been raised and answered before. If you only use captcha on a single page, not the whole app, you just need to wrap that page only with the CaptchaProvider. You just need to make sure that, there will be one and only one CaptchaProvider in your React tree at all time.
