### ISSUE TITLE
Google recaptcha script fails to load on Chromium due to CSP violation

### ISSUE THREAD

**Issue by hashibuto** [t49tran/react-google-recaptcha-v3#65]
`"react-google-recaptcha-v3": "^1.8.0"`

Using Chromium:
Version 87.0.4280.66 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

```
google-recaptcha-provider.tsx:131 Refused to load the script 'https://www.google.com/recaptcha/api.js?render=<redacted>&hl=en' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by wraithm** [comment]
@hashibuto How did you solve this?

**Comment by hashibuto** [comment]
> @hashibuto How did you solve this?

It's been awhile now, but if I recall correctly, I had to adjust the CSP within nginx to allow for the google domain.

**Comment by wraithm** [comment]
> > @hashibuto How did you solve this?
> 
> It's been awhile now, but if I recall correctly, I had to adjust the CSP within nginx to allow for the google domain.

Yeah, so I did that. I found that this react component is attaching the Google recaptcha script dynamically, such that you're kinda forced into using unsafe-inline.

I'd love it if there were some easy way to figure out the hash of the script that's gonna be attached, and I'd also love to figure out if that script is stable.
