### ISSUE TITLE
Why is v1.7.0 tagged as the latest release in the release list?

### ISSUE THREAD

**Issue by alextenb** [t49tran/react-google-recaptcha-v3#76]
HI, just a question. Why is 1.7.0 tagged as the latest release? The current npm version is 1.9.4.

**Comment by t49tran** [comment]
Hi @alextenb , thanks for bringing it up, creating a release from the tag in Github is something I often forget when I do a release via npm.

I have updated the latest release to v1.9.4, will add a Github action to handle this in the future.
