### ISSUE TITLE
Upgrading from v1.8.1 to 1.9.X breaks executeRecaptcha 

### ISSUE THREAD

**Issue by DennisBold** [t49tran/react-google-recaptcha-v3#80]
Hello,

We're currently using react 16.14.0 alongisde this package, due to various reasons (and packages) we can't go any further. There's also several react-* packages that are stuck at least a major version behined.

We tried to update the package from 1.8.1 to 1.9.4 (also tried all versions in between) but started getting an undefined function error. (executeRecaptcha is undefined)
We're essentially following the documentation with our usage, and it pretty much matches the `withGoogleReCaptcha` implementation in the README. I realise the README does state that `executeRecaptcha` may be removed in future versions. Does 1.9.X remove executeRecaptcha? If no, is there something we're missing?

Thanks in advance!

**Comment by t49tran** [comment]
Hi @DennisBold, react 16.14 should be compatible with 1.9.4. In 1.9.4, `executeRecaptcha` can be undefined when the google recaptcha script is being loaded, I will update the ReadMe for that.

When you upgrade from 1.8 to 1.9.4, add an undefined check before using `executeRecaptcha`.

Also, regarding `withGoogleRecpatcha`, I plan to remove it in the next version to remove the dependency on the `hoist` package and to reduce the size of the package.

**Comment by DennisBold** [comment]
Thanks @t49tran. We'll update things on our application and let you know how it goes!

Dennis
