### ISSUE TITLE
Recaptcha script tag have was added again when click link to transition between routes

### ISSUE THREAD

**Issue by meotimdihia** [t49tran/react-google-recaptcha-v3#89]
If these params have used: 
```javascript
      scriptProps={{
        async: true, // optional, default to false,
        defer: true, // optional, default to false
        appendTo: "head", // optional, default to "head", can be "head" or "body",
        nonce: undefined // optional, default undefined
      }}
```
Recaptcha script tag has was added again when clicking the link to transition between routes

**Comment by t49tran** [comment]
Thanks for reporting @meotimdihia , I will check this once I have some time.

**Comment by musme** [comment]
I have the same problem!

**Comment by t49tran** [comment]
Hi @meotimdihia, @musme can you guys please provide more information on the issue you have ? How you use `GoogleRecaptchaProvider` and what is the error and what do you think expected behaviour ? 

With the current limited information it is impossible for me to assist.

**Comment by meotimdihia** [comment]
@t49tran I have used Next.js and `react-google-recaptcha` .
I can't give example because you need a Recaptcha key but it is like this :
https://codesandbox.io/s/wizardly-silence-4jvnq?file=/pages/_app.js
When you click the link, the Recaptcha script will download again.

**Comment by meotimdihia** [comment]
I can't reproduce this bug on the basic example. I think it is related to my next.js app.

**Comment by t49tran** [comment]
Hi @meotimdihia, no worry, I think I understand your issue partly, just want to confirm with you to see that we are both on the same page. I will update you later on this issue.

**Comment by musme** [comment]
@t49tran, sorry man. I made a mistake. I put GoogleReCaptchaProvider inside another component that is rendering multiple times,

**Comment by t49tran** [comment]
I made an update on v1.9.5 that should resolve issue potentially causing this problem. I also updated the doc to provide some more information on how the provider should be used.
