### ISSUE TITLE
Implement badge prop

### ISSUE THREAD

**Issue by avishapiro01** [t49tran/react-google-recaptcha-v3#94]
Hi @t49tran, 

Thank you for creating this library.

Would you consider implementing a prop for the badge location of the recaptcha?

From the official docs:

![image](https://user-images.githubusercontent.com/46131316/131248640-5fc2639f-14f1-4769-84f4-8c94b1b44568.png)

https://developers.google.com/recaptcha/docs/invisible#render_param

Thanks!

**Comment by t49tran** [comment]
@avishapiro01 , thanks for bringing this to my attention. I will check and implement it when I have some free time.

**Comment by hadnet** [comment]
@t49tran if you can add the the theme prop for dark theme would be awesome too.
![dark-theme](https://user-images.githubusercontent.com/13828833/131938533-7d2e6d4b-2b58-42e3-ae61-1a287a547f5d.png)

**Comment by DjVreditel** [comment]
@t49tran, please check the PR above.
