### ISSUE TITLE
GoogleReCaptcha component spamming Reload request

### ISSUE THREAD

**Issue by phatNfqAsia** [t49tran/react-google-recaptcha-v3#95]
As I use the component as instructed, the component was sending multiple request relentlessly. I don't know if this is intentional :cry: 

![image](https://user-images.githubusercontent.com/39822773/131640049-bd634a41-bc6a-4dcc-bfba-da1fe54ddfb6.png)

**Comment by alejandrombc** [comment]
@phatNfqAsia am having the same issue how do you solve it?
