### ISSUE TITLE
No ReCaptcha client exists

### ISSUE THREAD

**Issue by phatNfqAsia** [t49tran/react-google-recaptcha-v3#96]
I set up ReCatpcha using Provider and hook as instructed, it does allow the form to be submitted but from the `recaptcha_en.js` it catch an error like this. I have enabled/disabled the ReCaptcha component but this problem still persist. And the `recaptcha_en.js` is also minified so I can not get any further info from there.

![image](https://user-images.githubusercontent.com/39822773/131640454-b287659f-236f-4f30-9ade-3d7a9a613414.png)

**Comment by phatNfqAsia** [comment]
Please ignore this, I am stupid enuff to keep the v2 implementation while v3 is a whole completely different thing

**Comment by t49tran** [comment]
Hi @phatNfqAsia, without code example there is nothing I can help. Also, please don't spam opening the issues. `recaptcha_en.js` is Google provided script and I couldn't help with debugging it.

**Comment by phatNfqAsia** [comment]
Oh very sorry @t49tran, I got a tired mind after a long day and does not investigate the problem thoroughly myself. it is because I use v2 method `window.grecaptcha.reset()` method which is not available in v3 use case. I remove that line of code and problem disappear. Just note this down in case anyone have trouble migrating v2 to v3 can see :grin:
