### ISSUE TITLE
Get a new Recaptcha token

### ISSUE THREAD

**Issue by Liam-OShea** [t49tran/react-google-recaptcha-v3#97]
Hi there,

I'm using this library to generate a Recaptcha token on my Registration page which I then verify to determine if I should make the user account. The problem is if the registration fails for some reason after validating the token, the user can not make a second attempt as the token has been invalidated after one use.

Is there a way to get a new token in this case using your library?

**Comment by t49tran** [comment]
Hi @Liam-OShea , please check the doc. You can use the hook `useGoogleRecaptcha` which will give you access to the `excecuteRecaptcha` function that will generate a new token when being invoked.
https://github.com/t49tran/react-google-recaptcha-v3#react-hook-usegooglerecaptcha-recommended-approach
