### ISSUE TITLE
Execute recaptcha function not defined?

### ISSUE THREAD

**Issue by sulismies** [t49tran/react-google-recaptcha-v3#98]
Hi,

I am using the first suggested method GoogleReCaptcha 
https://github.com/t49tran/react-google-recaptcha-v3#googlerecaptcha
inside a React component to get things done.

So far so good:
1. I get my token in handleVerify, 
2. I can succesfully pass the token to a backend (firebase functions)
3. The backend passes the token to https://recaptcha.google.com/recaptcha/api/siteverify and 
4. gets a response object and passes it to my react UI:
{ 
challenge_ts: "2021-09-05T05:16:23Z"
hostname: "localhost"
score: 0.9
success: true
...
 }

Everything seems to go smoothly, but in Chrome console I keep getting a warning message
"google-recaptcha.tsx:15 Execute recaptcha function not defined"

Any ideas how to eliminate that?

**Comment by t49tran** [comment]
Hi @sulismies thanks for asking the question. From what I can see I think everything is ok for you. The message you see is actually not an error, it's just a warning. For now you can ignore it.

For the next version I will update it so warning messages like this will be removed in production mode. I will also double check to see if there should be a warning message from `GoogleRecaptcha` component here.

**Comment by sulismies** [comment]
Many thanks for your quick answer. This is my first react app and therefore I have some doubts that I am missing something essential.
